name: Deploy wildcapture.io website to s3 blob storage

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: build
    runs-on: ubuntu-latest  
    steps:     
    - uses: actions/checkout@v2      
    - name: Build Application
      run: |
         npm install --force
         npm run build
         
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
         name: artifacts
         path: build/
         retention-days: 1
        
  Deploy:
    name: deploy
    needs: Build
    runs-on: ubuntu-latest 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
         name: artifacts
         path: build/
         
    - name: Deploy to s3
      uses: reggionick/s3-deploy@v3
      with:
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        folder: build
        
